### ISSUE TITLE
use semantic versioning

### ISSUE THREAD

**Issue by roubachof** [ThomasLebrun/XamarinBehaviorsToolkit#1]
I suggest you use http://semver.org/ to version your project.
MAJOR.MINOR.PATCH
So maybe, start with 0.1.0 instead of 0.0.1.

**Comment by ThomasLebrun** [comment]
I've planned to use this versionning once the first release (1.0.0) will be out.
For now, a patch, if needed, will simply be a new version.

Thanks!
